import 'package:get/get.dart';

import '../../service/network_manager.dart';
import '../add_service/add_service_controller.dart';
import '../admin_controllers/adminLoginScreenController/admin_login_screen_controller.dart';
import '../admin_controllers/adminSignupScreenController/admin_signup_screen_controller.dart';
import '../admin_controllers/all_employee_controller.dart/create_employee_controller.dart';
import '../admin_controllers/all_employee_controller.dart/edit_employee_controller.dart';
import '../auth_controller/loginScreenController/login_screen_controller.dart';
import '../auth_controller/otpScreenController/otp_verification_controller.dart';
import '../auth_controller/signupScreenController/signup_screen_controller.dart';
import '../bussiness/add_sub_salon_controller.dart';
import '../bussiness/admin/admin_dashboard_view_controller.dart';
import '../bussiness/bussiness_details_view_controller.dart';
import '../bussiness/bussiness_profile_create_view_controller.dart';
import '../bussiness/edit_bussones_profile_view_controller.dart';
import '../bussiness/multi_service_profile_create_view_controller.dart';
import '../bussiness/salon_services_employee_controller.dart';
import '../nav_admin_controller/nav_admin_controller.dart';
import '../nav_controller/nav_controller.dart';
import '../onboarding_view_controller/onboarding_view_controller.dart';
import '../profile/about_view_controller.dart';
import '../profile/account_settings_view_controller.dart';
import '../profile/add_address_view_controller.dart';
import '../profile/add_favourite_view_controller.dart';
import '../profile/add_new_payment_view_controller.dart';
import '../profile/edit_address_view_controller.dart';
import '../profile/help_view_controller.dart';
import '../profile/language_view_controller.dart';
import '../profile/myaddress_view_controller.dart';
import '../profile/setting_profile_view_controller.dart';
import '../profile/wallet_view_controller.dart';
import '../services_place_controllers/appointment_view_controller/appointment_view_controller.dart';
import '../services_place_controllers/booking_receipt_controller/booking_receipt_view_controller.dart';
import '../services_place_controllers/favourite_view_controller/favourite_view_controller.dart';
import '../services_place_controllers/haircut_and_styling_view_controller/haircut_and_styling_view_controller.dart';
import '../services_place_controllers/not_in_service_area_controller/not_service_area_controller.dart';
import '../services_place_controllers/service_by_address_view_controller/services_by_address_view_controller.dart';
import '../services_place_controllers/service_in_view_controller/service_in_view_controller.dart';
import '../services_view_controller/service_controller/service_controller.dart';
import '../services_view_controller/sub_service/sub_service_details_view_controller.dart';
import '../services_view_controller/sub_service/view_all_subservice_view_controller.dart';
import '../splash/splash_view_controller.dart';

class ControllerBinder extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => OnboardingViewController());
    Get.lazyPut(() => AppointmentController());
    Get.lazyPut(() => ServiceInViewController());
    Get.lazyPut(() => NotInServiceViewController());
    Get.lazyPut(() => NavigationController());
    Get.lazyPut(() => ServiceByAddressViewController());
    Get.lazyPut(() => HairCutAndStylingController());
    Get.lazyPut(() => LoginController());
    Get.lazyPut(() => OTPVerificationController());
    Get.lazyPut(() => SignUpController());
    Get.lazyPut(() => FavouriteViewController());
    Get.lazyPut(() => BookingReceiptDetailsController());
    Get.lazyPut(() => SettingProfileController());
    Get.lazyPut(() => WalletViewController());
    Get.lazyPut(() => AccountSettingsController());
    Get.lazyPut(() => AboutAppController());
    Get.lazyPut(() => LanguageController());
    Get.lazyPut(() => EditAddressController());
    Get.lazyPut(() => MyAddressesController());
    Get.lazyPut(() => AddAddressController());
    Get.lazyPut(() => PaymentMethodController());
    Get.lazyPut(() => HelpViewController());
    Get.lazyPut(() => SplashViewController());
    Get.lazyPut(() => AddFavoritesController());
    Get.lazyPut(() => BusinessProfileCreateViewController());
    Get.lazyPut(() => MultiServiceProfileCreateViewController());
    Get.lazyPut(() => AdminDashboardController());
    Get.lazyPut(() => AdminNavigationController());
    Get.lazyPut(() => ServiceController());
    Get.lazyPut(() => NetworkManager());
    Get.lazyPut(() => AdminLoginController());
    Get.lazyPut(() => AddServiceController());
    Get.lazyPut(() => AuthSignUpController());
    Get.lazyPut(() => SubServiceSalonViewController());
    Get.lazyPut(() => SubServiceDetailsController());
    Get.lazyPut(() => ViewAllSubServiceByAdminIdController());
    Get.lazyPut(() => BussinessDetailsViewController());
    Get.lazyPut(() => EditBusinessProfileCreateViewController());
    Get.lazyPut(() => SalonServicesEmployeeController());
    Get.lazyPut(() => CreateEmployeeController());
    Get.lazyPut(() => EditEmployeeController());
  }
}
