// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEVjSJM_nl3cqs-Tq2wRS8teOrRfkvVxE',
    appId: '1:166975517763:web:9ab779f90765798f4090f6',
    messagingSenderId: '166975517763',
    projectId: 'framie-c1450',
    authDomain: 'framie-c1450.firebaseapp.com',
    storageBucket: 'framie-c1450.firebasestorage.app',
    measurementId: 'G-LZ8P2CWBHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmshnDqNB7SDmlgjf8FKoWMNnvgbcoOhU',
    appId: '1:166975517763:android:ff22ffd94020d6aa4090f6',
    messagingSenderId: '166975517763',
    projectId: 'framie-c1450',
    storageBucket: 'framie-c1450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bggbR6ggHzgDi5NaIIPRpyZfOJEzAjY',
    appId: '1:166975517763:ios:bd9957f9496081184090f6',
    messagingSenderId: '166975517763',
    projectId: 'framie-c1450',
    storageBucket: 'framie-c1450.firebasestorage.app',
    iosBundleId: 'com.venturevilla.beauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_bggbR6ggHzgDi5NaIIPRpyZfOJEzAjY',
    appId: '1:166975517763:ios:bd9957f9496081184090f6',
    messagingSenderId: '166975517763',
    projectId: 'framie-c1450',
    storageBucket: 'framie-c1450.firebasestorage.app',
    iosBundleId: 'com.venturevilla.beauty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEVjSJM_nl3cqs-Tq2wRS8teOrRfkvVxE',
    appId: '1:166975517763:web:92cfa7a3d810c8b64090f6',
    messagingSenderId: '166975517763',
    projectId: 'framie-c1450',
    authDomain: 'framie-c1450.firebaseapp.com',
    storageBucket: 'framie-c1450.firebasestorage.app',
    measurementId: 'G-PX1JTEDETC',
  );
}
