on:
  push:
    branches:
      - main
    
name: "Build and Release Flutter App"
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --split-per-abi
      - name: push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.0.${{ github.run_number }}